# Generated by Django 5.2.1 on 2025-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_notes",
        ),
        migrations.RemoveField(
            model_name="event",
            name="sound_engineer",
        ),
        migrations.AddField(
            model_name="event",
            name="activation",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Activation",
            ),
        ),
    ]
