# Generated by Django 5.2.1 on 2025-12-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_activation_alter_event_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
