# Generated by Django 5.2.1 on 2025-12-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_event_google_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="google_calendar_id",
            field=models.CharField(
                blank=True,
                help_text="The Google Calendar ID for this venue (e.g., 'primary' or 'c_123...@group.calendar.google.com')",
                max_length=255,
                null=True,
            ),
        ),
    ]
